export type User = {
  firstName: string;
  lastName: string;
  age: number;
  visits: number;
  progress: number;
  status: string;
};

export const userDatas: User[] = [
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "adfs",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "dafadfasdf",
    lastName: "df",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "收到罚单",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿队首发水电费",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "是的发送",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "大法",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿方",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
  {
    firstName: "Tannsafasdfasdfasdfasdfer",
    lastName: "阿路附近九分裤垃圾饭卡及时反馈",
    age: 33,
    visits: 100,
    progress: 50,
    status: "Married",
  },
  {
    firstName: "Kevin",
    lastName: "Vandy",
    age: 27,
    visits: 200,
    progress: 100,
    status: "Single",
  },
];
